### ISSUE TITLE
py3 bytes vs str issue in postfligh

### ISSUE THREAD

**Issue by sheagcraig** [salopensource/sal-scripts#69]
```
Apr 15 2020 11:39:03 +0100     postflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/postflight.d/sal-postflight", line 102, in <module>
    main()
  File "/usr/local/munki/postflight.d/sal-postflight", line 95, in main
    ensure_launchd_loaded()
  File "/usr/local/munki/postflight.d/sal-postflight", line 88, in ensure_launchd_loaded
    if LAUNCHD not in loaded_launchds and os.path.exists(LAUNCHD_PATH):
TypeError: a bytes-like object is required, not 'str'
```

**Comment by pmamberti** [comment]
If worth anything I am seeing this as well, but devices check in to our sal instance.

**Comment by sheagcraig** [comment]
It's totally just a py3 thing that didn't get vetted prior to the release. Should be easy.

**Comment by sheagcraig** [comment]
That ought to do it.
