### ISSUE TITLE
BigSur Issue

### ISSUE THREAD

**Issue by Zolotkey** [salopensource/sal-scripts#76]
I am having issues with BigSur machines reporting in. It seems that some python modules are not found.

```regula:~ root# /usr/local/sal/bin/sal-submit
Traceback (most recent call last):
  File "/usr/local/sal/checkin_modules/munki_checkin.py", line 12, in <module>
    from munkilib import munkicommon
  File "/usr/local/munki/munkilib/munkicommon.py", line 35, in <module>
    from .info import *
  File "/usr/local/munki/munkilib/info.py", line 36, in <module>
    import LaunchServices
  File "/usr/local/sal/Python.framework/Versions/3.8/lib/python3.8/site-packages/LaunchServices/__init__.py", line 10, in <module>
    import CoreServices
  File "/usr/local/sal/Python.framework/Versions/3.8/lib/python3.8/site-packages/CoreServices/__init__.py", line 14, in <module>
    from CoreServices import (
  File "/usr/local/sal/Python.framework/Versions/3.8/lib/python3.8/site-packages/CoreServices/LaunchServices/__init__.py", line 16, in <module>
    objc.pathForFramework(
  File "/usr/local/sal/Python.framework/Versions/3.8/lib/python3.8/site-packages/objc/_dyld.py", line 136, in pathForFramework
    fpath, name, version = infoForFramework(dyld_find(path))
  File "/usr/local/sal/Python.framework/Versions/3.8/lib/python3.8/site-packages/objc/_dyld.py", line 130, in dyld_find
    return dyld_framework(filename, framework_name, version)
  File "/usr/local/sal/Python.framework/Versions/3.8/lib/python3.8/site-packages/objc/_dyld.py", line 98, in dyld_framework
    raise ImportError("Framework %s could not be found" % (framework_name,))
ImportError: Framework CoreServices could not be found```

**Comment by grahamgilbert** [comment]
Will need to update to PyObjc 6.2.2
