### ISSUE TITLE
Sal-Scripts fails to report to the Sal sever

### ISSUE THREAD

**Issue by Fallout476** [salopensource/sal-scripts#94]
been running into a problem with Sal-Scripts reporting to our Sal server. here is the output below.

** Details/Background **
2018 MBP running macOS 11.4 BigSur
started after I upgraded to BigSur from Catalina
so far i'm the only device in our org's fleet to have this problem
re-installs/reboots do not resolve the issue
Running Sal-Scripts 4.1.1, downloaded/installed today, reporting to Sal server 4.1.6 running in a docker container on CentOS7

** Output from debug **

REDACTED$ sudo /usr/local/sal/bin/sal-submit -d -v
Password:
2021-05-26 12:32:20,155 INFO sal-submit Version: 4.1.1
2021-05-26 12:32:20,155 DEBUG Sal client prefs:
2021-05-26 12:32:20,157 DEBUG 	ServerURL: REDACTED (prefs)
2021-05-26 12:32:20,157 DEBUG 	key: 75o3ca2u8v5y5krwl48ow6v2tsb55czz49uajjklmls8ns2cuok9hczbjeg8ahul79wagb6qxotob17ve7yrwvv8wndatfpxg69i6bqeol524qj3yreq0up7qu3fbfba (prefs)
2021-05-26 12:32:20,157 DEBUG 	BasicAuth: 1 (prefs)
2021-05-26 12:32:20,157 DEBUG 	SyncScripts: 1 (prefs)
2021-05-26 12:32:20,157 DEBUG 	SkipFacts: [] (prefs)
2021-05-26 12:32:20,157 DEBUG 	CACert: None (prefs)
2021-05-26 12:32:20,157 DEBUG 	SendOfflineReport: False (prefs)
2021-05-26 12:32:20,157 DEBUG 	SSLClientCertificate: None (prefs)
2021-05-26 12:32:20,157 DEBUG 	SSLClientKey: None (prefs)
2021-05-26 12:32:20,157 DEBUG 	MessageBlacklistPatterns: None (prefs)
2021-05-26 12:32:20,250 INFO Processing checkin modules...
Traceback (most recent call last):
  File "/usr/local/sal/checkin_modules/machine_checkin.py", line 208, in <module>
    main()
  File "/usr/local/sal/checkin_modules/machine_checkin.py", line 32, in main
    extras.update(process_system_profile())
  File "/usr/local/sal/checkin_modules/machine_checkin.py", line 45, in process_system_profile
    machine_results["serial"] = system_profile["SPHardwareDataType"][0]["serial_number"]
KeyError: 'SPHardwareDataType'
2021-05-26 12:38:23,709 DEBUG '/usr/local/sal/checkin_modules/sal_checkin.py' ran successfully
2021-05-26 12:38:23,710 DEBUG '/usr/local/sal/checkin_modules/munki_checkin.py' ran successfully
2021-05-26 12:38:23,710 DEBUG '/usr/local/sal/checkin_modules/profile_checkin.py' ran successfully
2021-05-26 12:38:23,710 DEBUG '/usr/local/sal/checkin_modules/machine_checkin.py' had errors during execution!
2021-05-26 12:38:23,710 DEBUG '/usr/local/sal/checkin_modules/apple_sus_checkin.py' ran successfully
2021-05-26 12:38:23,712 INFO Processing plugins...
2021-05-26 12:38:23,712 WARNING No external data plist found.
2021-05-26 12:38:23,721 DEBUG Using MacKeychainClient
2021-05-26 12:38:23,722 DEBUG Checkin submission:
2021-05-26 12:38:23,723 DEBUG {
    "Sal": {
        "extra_data": {
            "sal_version": "4.1.1",
            "key": "75o3ca2u8v5y5krwl48ow6v2tsb55czz49uajjklmls8ns2cuok9hczbjeg8ahul79wagb6qxotob17ve7yrwvv8wndatfpxg69i6bqeol524qj3yreq0up7qu3fbfba"
        },
        "facts": {
            "checkin_module_version": "1.1.0"
        }
    },
    "Munki": {
        "extra_data": {
            "munki_version": "5.2.3.4295",
            "manifest": "Testing",
            "runtype": "auto"
        },
        "facts": {
            "checkin_module_version": "1.2.0",
            "RunType": "auto",
            "StartTime": "2021-05-26 15:55:08 +0000",
            "EndTime": "2021-05-26 15:55:16 +0000",
            "arch": "x86_64",
            "date": "2021-05-26T15:55:08+00:00",
            "hostname": "REDACTED,
            "ibridge_model_name": "Apple T2 Security Chip",
            "ipv4_address": "REDACTED",
            "ipv6_address": "",
            "machine_model": "MacBookPro15,1",
            "machine_type": "laptop",
            "munki_version": "5.2.3.4295",
            "os_build_last_component": 71,
            "os_build_number": "20F71",
            "os_vers": "11.4",
            "os_vers_major": 11,
            "os_vers_minor": 4,
            "os_vers_patch": 0,
            "serial_number": "SERIAL#REDACTED",
            "x86_64_capable": true
        },
        "messages": [
            {
                "message_type": "WARNING",
              REDACTED
            },
            {
                "message_type": "WARNING",
                "text": "Could not process item sal-osquery for update. No pkginfo found in catalogs: testing"
            },
            {
                "message_type": "WARNING",
                REDACTED
            },
            {
                "message_type": "WARNING",
                "text": "Could not process item sal-osquery for optional install. No pkginfo found in catalogs: testing"
            },
            {
                "message_type": "WARNING",
                "text": "ChangeUpdateServerTesting.mobileconfig is a featured item but not an optional install"
            },
            {
                "message_type": "WARNING",
      REDACTED
            },
            {
                "message_type": "WARNING",
                REDACTED
            },
            {
                "message_type": "WARNING",
                REDACTED
            },
            {
                "message_type": "WARNING",
                "text": "sal-osquery is a featured item but not an optional install"
            },
            {
                "message_type": "WARNING",
                "text": "Company Portal MDM is a featured item but not an optional install"
            }
        ],
       REDACTED
                }
            },
            "Company Portal MDM 4.35.21050901": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Company Portal MDM 4.35.21050901",
                "data": {
                    "description": "Microsoft Intune is a Microsoft cloud-based management solution that provides for mobile device and operating system management.",
                    "display_name": "Company Portal MDM",
                    "installed_size": 58355,
                    "installed_version": "4.35.21050901",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
 REDACTED
                }
            },
            "1Password 7.8.4": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "1Password 7.8.4",
                "data": {
                    "description": "1Password is a password manager that goes beyond simple password storage by integrating directly with your web browser to automatically log you into websites, enter credit card information, fill registration forms, and easily generate strong passwords.",
                    "display_name": "1Password",
                    "installed_size": 215197,
                    "installed_version": "7.8.4",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "AdoptOpenJDK 12 12.0.2+10-201910130913": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "AdoptOpenJDK 12 12.0.2+10-201910130913",
                "data": {
                    "description": "AdoptOpenJDK 12 HotSpot",
                    "display_name": "AdoptOpenJDK 12",
                    "installed_size": 328204,
                    "installed_version": "12.0.2+10-201910130913",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Angry IP Scanner 3.7.6": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Angry IP Scanner 3.7.6",
                "data": {
                    "description": "Angry IP Scanner - fast and friendly network scanner",
                    "display_name": "Angry IP Scanner",
                    "installed_size": 1749,
                    "installed_version": "3.7.6",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "bigsurblocker 20201111": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "bigsurblocker 20201111",
                "data": {
                    "description": "",
                    "display_name": "bigsurblocker",
                    "installed_size": 169,
                    "installed_version": "20201111",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
       REDACTED
                }
            },
            "coconutBattery 3.9.5": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "coconutBattery 3.9.5",
                "data": {
                    "description": "Displays info about your laptop battery.",
                    "display_name": "coconutBattery",
                    "installed_size": 14251,
                    "installed_version": "3.9.5",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Git 2.31.0": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Git 2.31.0",
                "data": {
                    "description": "Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.",
                    "display_name": "Git for Mac",
                    "installed_size": 50923,
                    "installed_version": "2.31.0",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "GlobalProtect 5.2.2": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "GlobalProtect 5.2.2",
                "data": {
                    "description": "",
                    "display_name": "GlobalProtect",
                    "installed_size": 36080,
                    "installed_version": "5.2.2",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "GoogleChrome 91.0.4472.77": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "GoogleChrome 91.0.4472.77",
                "data": {
                    "description": "Chrome is a fast, simple, and secure web browser, built for the modern web.",
                    "display_name": "Google Chrome",
                    "installed_size": 100630,
                    "installed_version": "91.0.4472.77",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "LastPass 4.4.0": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "LastPass 4.4.0",
                "data": {
                    "description": "",
                    "display_name": "LastPass",
                    "installed_size": 12161,
                    "installed_version": "4.4.0",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Malwarebytes (newer than 4.7.9.3978)": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Malwarebytes (newer than 4.7.9.3978)",
                "data": {
                    "description": "Proven Malwarebytes technology crushes the growing threat of Mac malware.\nSo you are protected and your machine keeps running silky smooth.\nFinally, cybersecurity smart enough for the Mac.",
                    "display_name": "Malwarebytes",
                    "installed_size": 55441,
                    "installed_version": "(newer than 4.7.9.3978)",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Microsoft Remote Desktop 10.5.1": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Microsoft Remote Desktop 10.5.1",
                "data": {
                    "description": "With the Microsoft Remote Desktop app, you can connect to a remote PC and your work resources from almost anywhere. Experience the power of Windows with RemoteFX in a Remote Desktop client designed to help you get your work done wherever you are.",
                    "display_name": "Microsoft Remote Desktop",
                    "installed_size": 65498,
                    "installed_version": "10.5.1",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "MSTeams 1.00.411161": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "MSTeams 1.00.411161",
                "data": {
                    "description": "Microsoft Teams is the new chat-centered workspace in Office 365. Keep all your content, tools, people, and conversations together in one place.",
                    "display_name": "Microsoft Teams",
                    "installed_size": 251577,
                    "installed_version": "1.00.411161",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "NoMAD 1.2.2": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "NoMAD 1.2.2",
                "data": {
                    "description": "NoMAD is a helpful replacement for Active Directory bindings, using Kerberos and other resources to provide Active Directory services without a fragile binding plugin",
                    "display_name": "NoMAD",
                    "installed_size": 15875,
                    "installed_version": "1.2.2",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Office2019Suite 16.49.0": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Office2019Suite 16.49.0",
                "data": {
                    "description": "",
                    "display_name": "Office2019Suite",
                    "installed_size": 9324660,
                    "installed_version": "16.49.0",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "OneDrive 21.30.211": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "OneDrive 21.30.211",
                "data": {
                    "description": "\n              Get to your files from anywhere, on any device, with Microsoft OneDrive. Share and work together with anyone in your work and life. With OneDrive for Business, you also get storage for your work files so you can share and collaborate on them with other people at your work or school/university. The OneDrive app for Mac makes it easy to work with your OneDrive files on your Mac.",
                    "display_name": "OneDrive",
                    "installed_size": 172977,
                    "installed_version": "21.30.211",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "OpenJDK 12.0.2": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "OpenJDK 12.0.2",
                "data": {
                    "description": "",
                    "display_name": "OpenJDK",
                    "installed_size": 292834,
                    "installed_version": "12.0.2",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "OpenJDK 12 12.0.2": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "OpenJDK 12 12.0.2",
                "data": {
                    "description": "OpenJDK is a free and open-source implementation of the Java Platform, Standard Edition.",
                    "display_name": "OpenJDK 12",
                    "installed_size": 313117,
                    "installed_version": "12.0.2",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Packages 1.2.9": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Packages 1.2.9",
                "data": {
                    "description": "Whenever you need to create an installation package or distribution for Mac OS X 10.5 or later, Packages is the powerful and flexible solution you're looking for.",
                    "display_name": "Packages",
                    "installed_size": 12765,
                    "installed_version": "1.2.9",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Privileges 1.5.2": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Privileges 1.5.2",
                "data": {
                    "description": "Privileges.app for macOS is designed to allow users to work as a standard user for day-to-day use, by providing a quick and easy way to get administrator rights when needed. When you do need admin rights, you can get them by clicking on the Privileges icon in your Dock.",
                    "display_name": "Privileges",
                    "installed_size": 6335,
                    "installed_version": "1.5.2",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "sal_scripts 4.1.1": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "sal_scripts 4.1.1",
                "data": {
                    "description": "Client side scripts for Sal.",
                    "display_name": "sal_scripts",
                    "installed_size": 81394,
                    "installed_version": "4.1.1",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            REDACTED
                }
            },
            "Slack 4.16.2": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Slack 4.16.2",
                "data": {
                    "description": "Slack is a platform for team communication: everything in one place, instantly searchable, available wherever you go.",
                    "display_name": "Slack",
                    "installed_size": 78792,
                    "installed_version": "4.16.2",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "SuspiciousPackageApp 3.5.3": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "SuspiciousPackageApp 3.5.3",
                "data": {
                    "description": "Suspicious Package: An Application for Inspecting OS X Installer Packages",
                    "display_name": "Suspicious Package App",
                    "installed_size": 6147,
                    "installed_version": "3.5.3",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "TextMate2 2.0.19": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "TextMate2 2.0.19",
                "data": {
                    "description": "TextMate brings Apple's approach to operating systems into the world of text editors. By bridging UNIX underpinnings and GUI, TextMate cherry-picks the best of both worlds to the benefit of expert scripters and novice users alike.",
                    "display_name": "TextMate 2",
                    "installed_size": 23053,
                    "installed_version": "2.0.19",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Visual Studio Code 1.56.2": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Visual Studio Code 1.56.2",
                "data": {
                    "description": "Code combines the streamlined UI of a modern editor with rich code assistance and navigation, and an integrated debugging experience \u2013 without the need for a full IDE.",
                    "display_name": "Visual Studio Code",
                    "installed_size": 178801,
                    "installed_version": "1.56.2",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "VMwareFusion12 12.1.2": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "VMwareFusion12 12.1.2",
                "data": {
                    "description": "VMware Fusion is the easiest, fastest, and most reliable way to run Windows and other x86 based operating systems on a Mac without rebooting.",
                    "display_name": "VMWare Fusion Pro 12",
                    "installed_size": 637150,
                    "installed_version": "12.1.2",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            },
            "Webex Teams 3.0.13538.0": {
                "date_managed": "2021-05-26T16:32:21.548475+00:00",
                "status": "PRESENT",
                "name": "Webex Teams 3.0.13538.0",
                "data": {
                    "description": " ",
                    "display_name": "Webex Teams",
                    "installed_size": 111699,
                    "installed_version": "3.0.13538.0",
                    "type": "ManagedInstalls",
                    "self_serve": "False"
                }
            }
        }
    },
    "Profiles": {
        "facts": {
            "checkin_module_version": "1.0.0"
        },
        "managed_items": {
            "NoMAD AD/Shares": {
                "name": "NoMAD AD/Shares",
                "date_managed": "2021-04-26 21:28:25 +0000",
                "status": "PRESENT",
                "data": {
                    "payload 1": {
                        "PayloadContent": {
                            "ADDomain": "REDACTED",
                            "ChangePasswordType": "Kerberos",
                            "KerberosRealm": "REDACTED",
                            "LocalPasswordSync": true,
                            "LocalPasswordSyncOnMatchOnly": true,
                           REDACTED
                            },
                            "PersistExpiration": true,
                            "RenewTickets": true,
                            "SecondsToRenew": 3600,
                            "SelfServicePath": "/Applications/Managed Software Center.app",
                            "UseKeychain": true,
                            "UserSwitch": true
                        },
                        "PayloadDisplayName": "NoMAD",
                        "PayloadIdentifier": "com.trusourcelabs.NoMAD",
                        "PayloadType": "com.trusourcelabs.NoMAD",
                        "PayloadUUID": "E9892287-5EF9-4032-9794-8DDFC74BD7B8",
                        "PayloadVersion": 1
                    },
                    "payload 2": {
                        "PayloadContent": {
                            "Shares": [
                                {
                                    "AutoMount": true,
                                    "ConnectedOnly": false,
                                    "Name": "Departments",
                                    "URL": "REDACTED"
                                },
                                {
                                    "AutoMount": true,
                                    "ConnectedOnly": false,
                                    "Name": "Corporate",
                                    "URL": "REDACTED"
                                },
                                {
                                    "AutoMount": true,
                                    "ConnectedOnly": false,
                                    "Name": "Scratch",
                                    "URL": "REDACTED"
                                },
                                {
                                    "AutoMount": true,
                                    "ConnectedOnly": false,
                                    "Name": "Home",
                                    "URL": "REDACTED"
                                }
                            ]
                        },
                        "PayloadDisplayName": "NoMAD Shares",
                        "PayloadIdentifier": "menu.nomad.shares",
                        "PayloadType": "menu.nomad.shares",
                        "PayloadUUID": "DE6D028E-A6AA-4383-AE88-9C672467EF00",
                        "PayloadVersion": 1
                    },
                    "payload_types": "com.trusourcelabs.NoMAD, menu.nomad.shares",
                    "profile_description": "This Profile configures the use of NoMAD to apply shares and Active Directory services",
                    "identifier": "org.REDACTED.F7DCB458-0204-4182-A8BB-8D5378211AE7",
                    "organization": "REDACTED",
                    "uuid": "259C689A-F270-455D-ACC3-5F827222014A",
                    "verification_state": ""
                }
            },
            "MunkiDev": {
                "name": "MunkiDev",
                "date_managed": "2021-01-28 14:45:43 +0000",
                "status": "PRESENT",
                "data": {
                    "payload 1": {
                        "PayloadContent": {
                            "CatalogURL": "http://munkidev.REDACTED/catalogs",
                            "ClientIdentifier": "Testing",
                            "DaysBetweenNotifications": 1,
                            "FollowHTTPRedirects": "none",
                            "IconURL": "http://munkidev.REDACTED/icons",
                            "InstallAppleSoftwareUpdates": true,
                            "InstallRequiresLogout": false,
                            "LogFile": "/Library/Managed Installs/Logs/ManagedSoftwareUpdate.log",
                            "LogToSyslog": true,
                            "LoggingLevel": 1,
                            "MSUDebugLogEnabled": true,
                            "ManagedInstallDir": "/Library/Managed Installs",
                            "PackageURL": "http://munkidev.REDACTED/pkgs",
                            "PackageVerificationMode": "hash",
                            "ShowOptionalInstallsForHigherOSVersions": false,
                            "ShowRemovalDetail": true,
                            "SoftwareRepoURL": "http://munkidev.REDACTED/",
                            "SuppressAutoInstall": false,
                            "SuppressLoginwindowInstall": false,
                            "SuppressStopButtonOnInstall": true,
                            "SuppressUserNotification": false,
                            "UnattendedAppleUpdates": true,
                            "UseNotificationCenterDays": 3
                        },
                        "PayloadDisplayName": "Munki",
                        "PayloadIdentifier": "com.REDACTED.ProfileCreator.D4613D67-8B52-420A-9035-74660B4BFA7C.ManagedInstalls.359CF715-4E24-489E-A061-FD4ABD8FB6A5",
                        "PayloadOrganization": "REDACTED",
                        "PayloadType": "ManagedInstalls",
                        "PayloadUUID": "359CF715-4E24-489E-A061-FD4ABD8FB6A5",
                        "PayloadVersion": 1
                    },
                    "payload_types": "ManagedInstalls",
                    "profile_description": "None",
                    "identifier": "REDACTED.ProfileCreator.D4613D67-8B52-420A-9035-74660B4BFA7C",
                    "organization": "REDACTED",
                    "uuid": "D4613D67-8B52-420A-9035-74660B4BFA7C",
                    "verification_state": ""
                }
            },
            "Management Profile": {
                "name": "Management Profile",
                "date_managed": "2021-02-19 16:38:38 +0000",
                "status": "PRESENT",
                "data": {
                    "payload 1": {
                        "PayloadContent": {},
                        "PayloadDescription": "Credential Profile for installing root certificate",
                        "PayloadDisplayName": "Credential Profile",
                        "PayloadIdentifier": "www.windowsintune.com.credentials",
                        "PayloadOrganization": "Microsoft",
                        "PayloadType": "com.apple.security.root",
                        "PayloadUUID": "16fb2545-152c-40de-9aca-9dcc799867ed",
                        "PayloadVersion": 1
                    },
                    "payload 2": {
                        "PayloadContent": {},
                        "PayloadDescription": "SCEP Profile for issuing a device certificate",
                        "PayloadDisplayName": "SCEP Profile",
                        "PayloadIdentifier": "Microsoft.Profiles.SCEP",
                        "PayloadOrganization": "REDACTED",
                        "PayloadType": "com.apple.security.scep",
                        "PayloadUUID": "8E1495C5-535B-4689-88C6-244315327A36",
                        "PayloadVersion": 1
                    },
                    "payload 3": {
                        "PayloadContent": {
                            "AccessRights": 8191,
                            "CheckInURL": "https://i.manage.microsoft.com/DeviceGatewayProxy/ioscheckinhandler.ashx?Platform=MacMDM",
                            "CheckOutWhenRemoved": true,
                            "IdentityCertificateUUID": "REDACTED",
                            "ServerCapabilities": [
                                "com.apple.mdm.per-user-connections"
                            ],
                            "ServerURL": "https://i.manage.microsoft.com/DeviceGatewayProxy/ioshandler.ashx?Platform=MacMDM",
                            "SignMessage": false,
                            "Topic": "com.apple.mgmt.External.bbead177-ab07-REDACTED-18b20271983d",
                            "UseDevelopmentAPNS": false
                        },
                        "PayloadDescription": "Install this profile to get access to your company apps",
                        "PayloadDisplayName": "Management Profile",
                        "PayloadIdentifier": "Microsoft.Payloads.MDM",
                        "PayloadOrganization": "REDACTED",
                        "PayloadType": "com.apple.mdm",
                        "PayloadUUID": "67A5265B-12D4-4EB5-A2B3-72C683E33BCF",
                        "PayloadVersion": 1
                    },
                    "payload 4": {
                        "PayloadContent": {},
                        "PayloadDescription": "Credential Profile for installing root certificate",
                        "PayloadDisplayName": "Credential Profile",
                        "PayloadIdentifier": "www.windowsintune.com.credentials",
                        "PayloadOrganization": "Microsoft",
                        "PayloadType": "com.apple.security.root",
                        "PayloadUUID": "dc37b0d8-77a0-4941-95REDACTED34582b",
                        "PayloadVersion": 1
                    },
                    "payload_types": "com.apple.security.root, com.apple.security.scep, com.apple.mdm, com.apple.security.root",
                    "profile_description": "Install this profile to get access to your company apps",
                    "identifier": "Microsoft.Profiles.MDM",
                    "organization": "REDACTED",
                    "uuid": "C539BE6C-F080-4B24REDACTED6A4D6",
                    "verification_state": "verified"
                }
            }
        }
    },
    "Apple Software Update": {
        "facts": {
            "checkin_module_version": "1.1.0",
            "catalog": "https://swscan.apple.com/content/catalogs/others/index-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz",
            "last_check": "2021-05-26T16:26:18+00:00"
        },
        "managed_items": {
            "macOS 11.1": {
                "date_managed": "2021-01-28T02:42:14+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "11.1"
                }
            },
            "MRTConfigData": {
                "date_managed": "2021-05-17T22:05:41+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "1.78"
                }
            },
            "XProtectPlistConfigData": {
                "date_managed": "2021-05-14T23:39:58+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "2146"
                }
            },
            "macOS 11.2": {
                "date_managed": "2021-02-08T22:42:09+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "11.2"
                }
            },
            "macOS 11.2.1": {
                "date_managed": "2021-02-09T23:48:42+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "11.2.1"
                }
            },
            "macOS 11.2.2": {
                "date_managed": "2021-02-26T01:22:09+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "11.2.2"
                }
            },
            "macOS 11.2.3": {
                "date_managed": "2021-03-09T03:03:17+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "11.2.3"
                }
            },
            "macOS 11.3": {
                "date_managed": "2021-04-27T01:38:44+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "11.3"
                }
            },
            "macOS 11.3.1": {
                "date_managed": "2021-05-17T21:20:59+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "11.3.1"
                }
            },
            "macOS 11.4": {
                "date_managed": "2021-05-26T17:43:55+00:00",
                "status": "PRESENT",
                "data": {
                    "type": "Apple SUS Install",
                    "version": "11.4"
                }
            }
        },
        "update_history": []
    },
    "plugin_results": []
}
2021-05-26 12:38:23,726 DEBUG Sending report
2021-05-26 12:38:23,731 DEBUG Starting new HTTPS connection (1): sal.REDACTED.org:443
2021-05-26 12:38:24,182 DEBUG https://REDACTED:443 "POST /checkin/ HTTP/1.1" 400 47
2021-05-26 12:38:24,183 DEBUG Response HTTP 400: Checkin JSON is missing required key "Machine"!
Traceback (most recent call last):
  File "/usr/local/sal/bin/sal-submit", line 391, in <module>
    main()
  File "/usr/local/sal/bin/sal-submit", line 85, in main
    send_inventory(submission["Machine"]["extra_data"]["serial"])
KeyError: 'Machine'

**Comment by grahamgilbert** [comment]
I genuinely missed this somehow - I assume it's not an issue anymore?
